apiVersion: k8s.humalect.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application1
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: humalect-core-v2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: humalect-core-v2
  name: application-sample
  namespace: default
  finalizers:
    - finalizers.humalect.com/application
spec:
  cloudRegion: ap-south-1
  cloudProvider: aws
  deploymentYamlManifest:
    metadata:
      name: rest-test-manav-humalect-dev
      namespace: default
      labels:
        branchName: master
        managedBy: humalect
        organization: organizati-56a4f-bcb2-4a01-9b9b-b6bd872115ea
        deploymentId: 6456ac2505b0e5948261523b
        projectName: rest
        environmentName: default
    spec:
      selector:
        matchLabels:
          app: rest-test-manav-humalect-dev
      replicas: 3
      template:
        metadata:
          labels:
            app: rest-test-manav-humalect-dev
            deploymentId: 6456ac2505b0e5948261511
            managedBy: humalect
        spec:
          containers:
            - name: back-end
              image: "073328469200.dkr.ecr.ap-south-1.amazonaws.com/rest:e2f73a3ee70eca391a03634b9666cce1f82675d9"
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80
              envFrom: []
          volumes: []
  serviceYamlManifest:
    metadata:
      name: rest-test-manav-humalect-dev-svc
      labels:
        branchName: master
        managedBy: humalect
        organization: organizati-57596a4f-bcb2-4a01-9b9b-b6bd872115ea
        deploymentId: 6456ac2505b0e5948261523b
    spec:
      type: ClusterIP
      selector:
        app: rest-test-manav-humalect-dev
      ports:
        - port: 80
          targetPort: 80
  ingressYamlManifest:
    metadata:
      name: test-manav-humalect-dev
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
      labels:
        domain: manav.humalect.dev
        branchName: master
        managedBy: humalect
        organization: organizati-57596a4f-bcb2-4a01-9b9b-b6bd872115ea
        deploymentId: 6456ac2505b0e5948261523b
    spec:
      tls:
        - hosts:
            - test.manav.humalect.dev
          secretName: test-manav-humalect-dev
      rules:
        - host: test.manav.humalect.dev
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: rest-test-manav-humalect-dev-svc
                    port:
                      number: 80
  secretManagerName: test-rest-165m
  managedBy: humalect
