# permissions for end users to view deploymentsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymentset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: humalect-core-v2
    app.kubernetes.io/part-of: humalect-core-v2
    app.kubernetes.io/managed-by: kustomize
  name: deploymentset-viewer-role
rules:
- apiGroups:
  - k8s.humalect.com
  resources:
  - deploymentsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.humalect.com
  resources:
  - deploymentsets/status
  verbs:
  - get
